// Zomic marketing — blog content (placeholder posts, structured so
// real posts can be swapped in later).
export const POSTS = [
  {
    slug: 'first-reply-speed',
    title: 'The first reply is the whole game',
    excerpt: 'Why the agent who replies in 4 seconds wins the deal, and how to make sure it is you — on WhatsApp, every time.',
    tag: 'WhatsApp',
    readTime: '4 min read',
    date: '2026-08-12',
    author: 'Aisha Khan',
    color: 'linear-gradient(135deg, #A8E6C1, #C9BBFF)',
    body: [
      { type: 'p', text: 'If you sell anything where the customer messages five competitors at once — real estate, agencies, local services — the deal almost always goes to whoever replies first. Not the cheapest. Not the best-known. The fastest.' },
      { type: 'p', text: 'The data is brutal. A lead contacted within 5 minutes is 21x more likely to convert than one contacted after 30 minutes. After an hour, your odds are barely better than cold outreach.' },
      { type: 'h2', text: 'Why WhatsApp changed everything' },
      { type: 'p', text: 'Email used to give you a few hours. WhatsApp gives you minutes. A buyer who messages you on WhatsApp is sitting with their phone in their hand, ready to talk right now. If you reply in 4 hours, they have already booked a viewing with someone faster.' },
      { type: 'p', text: 'This is why we built instant auto-reply into Zomic. The moment a lead arrives — from a form, an ad, or a direct message — Zomic replies on WhatsApp with the relevant details and an offer to continue the conversation. You step in when they respond, already warmed up.' },
      { type: 'h2', text: 'How to do it without sounding like a bot' },
      { type: 'ul', items: [
        'Reply instantly with something specific to what they asked, not a generic "thanks for your interest".',
        'Offer a concrete next step — a viewing, a call slot, a piece of information — not "we will get back to you".',
        'Pause the automation the moment they reply. The bot warms them up; a human closes.',
        'Keep the tone short and human. WhatsApp is a chat, not a press release.',
      ] },
      { type: 'p', text: 'The teams that win are not the ones with the best product. They are the ones who show up first, every time. Make sure that is you.' },
    ],
  },
  {
    slug: 'crm-without-email-is-half-a-crm',
    title: 'A CRM without an email system is half a CRM',
    excerpt: 'Why bolting a separate email tool onto your CRM costs you leads, money, and your sanity — and what changes when they live together.',
    tag: 'Email',
    readTime: '5 min read',
    date: '2026-08-05',
    author: 'Marco Diaz',
    color: 'linear-gradient(135deg, #BFE3F5, #C9BBFF)',
    body: [
      { type: 'p', text: 'Most CRMs track your deals. Almost none of them help you actually move them. The biggest gap? Email. You track a lead in your CRM, then switch to a separate email tool to actually talk to them, then copy-paste the reply back into the CRM as a note. Every step is a place to lose context.' },
      { type: 'h2', text: 'The hidden cost of two tools' },
      { type: 'p', text: 'When your CRM and your email platform are separate, three things break: your segments go stale the moment a lead moves stages, your campaign audience is always a CSV export out of date, and your reps log nothing because logging is manual.' },
      { type: 'p', text: 'Zomic Mail fixes all three. Segments are live — they pull straight from your pipeline, so a lead who just moved to "Interested" is in tonight’s campaign automatically. No exports. No stale lists.' },
      { type: 'h2', text: 'One bill, one place, one source of truth' },
      { type: 'p', text: 'The math is simple: one tool instead of two, one bill instead of two, and one place where every conversation lives. Your reps stop logging because logging is automatic. Your campaigns stop going to the wrong people because the audience updates itself.' },
    ],
  },
  {
    slug: 'lead-scoring-that-actually-works',
    title: 'Lead scoring that actually works (and not the kind nobody uses)',
    excerpt: 'Most lead scores are a made-up number nobody trusts. Here is how Conversion Signal scores leads by what they actually do — and why your reps will finally use it.',
    tag: 'Intelligence',
    readTime: '6 min read',
    date: '2026-07-28',
    author: 'Priya Sharma',
    color: 'linear-gradient(135deg, #FFE9A8, #FFD6A8)',
    body: [
      { type: 'p', text: 'Every CRM has a lead score field. Almost nobody uses it. The reason is simple: most lead scores are a number a consultant made up once, weighted by gut feel, that has no relationship to whether a lead will actually buy.' },
      { type: 'h2', text: 'Score behaviour, not demographics' },
      { type: 'p', text: 'Conversion Signal does not care about a lead’s job title. It cares about what they do: did they open your email three times today? Did they reply on WhatsApp? Did they visit your pricing page twice this week? Behaviour predicts intent far better than firmographics.' },
      { type: 'h2', text: 'Learn from your wins' },
      { type: 'p', text: 'The score is not static. Zomic looks at the leads you have actually closed and weights the behaviours that correlated with winning. So the score gets smarter the more you use it — and it reflects how your team sells, not a generic formula.' },
      { type: 'p', text: 'The result is a score your reps actually trust, because it is built from your own data. They start calling the 90s before you have to tell them to.' },
    ],
  },
  {
    slug: 'whatsapp-automation-within-policy',
    title: 'WhatsApp automation that stays within Meta’s policy',
    excerpt: 'WhatsApp is strict about what you can automate. Here is how to run sequences and broadcasts without getting your number banned.',
    tag: 'WhatsApp',
    readTime: '7 min read',
    date: '2026-07-15',
    author: 'Aisha Khan',
    color: 'linear-gradient(135deg, #A8E6C1, #BFE3F5)',
    body: [
      { type: 'p', text: 'WhatsApp is the highest-converting channel most teams have. It is also the easiest one to get banned from, because Meta’s policy on automated messaging is strict and enforced. Here is how to stay on the right side of it.' },
      { type: 'h2', text: 'The 24-hour rule' },
      { type: 'p', text: 'You can send free-form messages to a user for 24 hours after they last message you. After that, you can only send approved template messages. Zomic handles this automatically — free-form inside the window, templates outside it.' },
      { type: 'h2', text: 'Templates, approved' },
      { type: 'p', text: 'Template messages have to be pre-approved by Meta. Zomic lets you submit and manage templates inside the app, and tracks approval status so you never accidentally try to send something that is still pending.' },
      { type: 'p', text: 'Get this right and WhatsApp becomes your best channel. Get it wrong and your number gets suspended. We built Zomic to make the right way the easy way.' },
    ],
  },
  {
    slug: 'from-spreadsheet-to-pipeline',
    title: 'From spreadsheet to pipeline in an afternoon',
    excerpt: 'A practical migration guide for teams moving from a lead-tracking spreadsheet to their first real CRM — without losing data or your mind.',
    tag: 'Getting started',
    readTime: '5 min read',
    date: '2026-07-02',
    author: 'Tom Becker',
    color: 'linear-gradient(135deg, #C9BBFF, #FFD6A8)',
    body: [
      { type: 'p', text: 'Every team’s first CRM is a spreadsheet. It works, until it does not — until you have hundreds of leads, multiple reps, and no idea who is supposed to follow up with whom. Here is how to move without the pain.' },
      { type: 'h2', text: 'Export, map, import' },
      { type: 'p', text: 'Export your sheet as CSV. Map your columns to Zomic’s lead fields (name, phone, email, status, source, notes). Import. Zomic deduplicates on email and phone automatically, so you will not end up with the same lead three times.' },
      { type: 'h2', text: 'Recreate your stages' },
      { type: 'p', text: 'Whatever columns you used as status — "new", "contacted", "won" — become your pipeline stages. Drag-and-drop to reorder. You can change them anytime.' },
      { type: 'p', text: 'The whole thing takes an afternoon. And unlike your spreadsheet, this one will not break when you add a second rep.' },
    ],
  },
  {
    slug: 'why-design-matters-in-a-crm',
    title: 'Why design matters in a CRM (yes, really)',
    excerpt: 'Ugly software gets used less. Used-less software means missing data, missed follow-ups, and missed revenue. Design is not a luxury in a CRM — it is a revenue decision.',
    tag: 'Product',
    readTime: '4 min read',
    date: '2026-06-20',
    author: 'Marco Diaz',
    color: 'linear-gradient(135deg, #FFC2C2, #C9BBFF)',
    body: [
      { type: 'p', text: 'CRMs have a reputation for being painful to use. That reputation is earned. And it costs you money, in a way most teams never measure.' },
      { type: 'h2', text: 'Used-less means useless' },
      { type: 'p', text: 'A CRM your reps avoid is a CRM with half-empty data. Half-empty data means your forecasts are guesses, your coaching is blind, and your best leads get forgotten. The root cause is not laziness — it is that the tool is unpleasant to open.' },
      { type: 'h2', text: 'Calm is a feature' },
      { type: 'p', text: 'We designed Zomic to feel calm: soft colours, generous spacing, fast interactions, no clutter. The goal is a tool your team opens without dread. Because the CRM they open is the CRM that has complete data. And complete data is where revenue lives.' },
    ],
  },
];
