// Flazyn marketing — blog content. Each body is a list of blocks
// ({ type: 'p' | 'h2' | 'ul' }) so the template and prerenderer stay simple.

export const POSTS = [
  {
    slug: 'first-reply-speed',
    title: 'The first reply is the whole game',
    description: 'Why response speed decides conversational sales, and how to reply to every lead in minutes without sounding like a bot.',
    tag: 'WhatsApp',
    readTime: '4 min read',
    date: '2026-09-30',
    author: 'Flazyn Team',
    image: '/images/blog-1.webp',
    imageAlt: 'A woman smiling while reading a message on her phone',
    body: [
      { type: 'p', text: 'If you sell anything where a customer contacts several businesses at once — property, agency services, local trades, education — the deal very often goes to whoever replies first. Not the cheapest. Not the best known. The fastest.' },
      { type: 'p', text: 'Research on lead response has pointed the same way for years: the odds of reaching and qualifying a lead fall sharply within the first hour. A lead that waits until tomorrow has usually spoken to someone else already.' },
      { type: 'h2', text: 'Why messaging raised the stakes' },
      { type: 'p', text: 'Email used to give you a few hours. Messaging gives you minutes. A buyer who messages you on WhatsApp is holding their phone right now and expects a conversation, not a ticket number.' },
      { type: 'p', text: 'That is why instant, relevant first replies are a core part of Flazyn. When a lead arrives from a form, an ad or a direct message, Flazyn is designed to send a helpful first message and put the conversation in front of the right person on your team.' },
      { type: 'h2', text: 'How to reply fast without sounding like a bot' },
      { type: 'ul', items: [
        'Answer what they actually asked — not a generic “thanks for your interest”.',
        'Offer a concrete next step: a call slot, a viewing time, a piece of information.',
        'Hand over to a human the moment the lead replies. Automation warms up; people close.',
        'Keep it short. Messaging is a chat, not a press release.',
      ] },
      { type: 'p', text: 'The teams that win are rarely the ones with the biggest budget. They are the ones who show up first, every time.' },
    ],
  },
  {
    slug: 'whatsapp-automation-within-policy',
    title: 'WhatsApp automation that respects Meta’s rules',
    description: 'Opt-in, the 24-hour customer service window and message templates, explained in plain English for sales teams.',
    tag: 'Compliance',
    readTime: '5 min read',
    date: '2026-09-30',
    author: 'Flazyn Team',
    image: '/images/blog-2.webp',
    imageAlt: 'A shop owner in an apron checking messages on his phone',
    body: [
      { type: 'p', text: 'WhatsApp is the most personal channel a business can use, which is exactly why Meta protects it carefully. Automation on the WhatsApp Business Platform works well — as long as you follow a few clear rules.' },
      { type: 'h2', text: 'Rule 1: Get opt-in first' },
      { type: 'p', text: 'You may only message people who have agreed to hear from your business on WhatsApp. Collect that consent clearly — on a form, at checkout, or in conversation — and keep a record of it. Flazyn stores opt-in status on every contact so your team always knows who can be messaged.' },
      { type: 'h2', text: 'Rule 2: Respect the 24-hour window' },
      { type: 'p', text: 'When a customer messages you, a customer service window opens. Inside it you can reply freely. Outside it, you can only start a conversation with a pre-approved message template. Flazyn shows the window on every conversation and switches to templates when it closes.' },
      { type: 'h2', text: 'Rule 3: Use approved templates' },
      { type: 'p', text: 'Templates are reviewed by Meta before you can use them. Keep them useful and specific, avoid anything that reads like spam, and always make it easy for people to opt out.' },
      { type: 'ul', items: [
        'Only message contacts who opted in.',
        'Reply freely inside the 24-hour window.',
        'Use approved templates to start conversations outside it.',
        'Honour opt-out requests immediately.',
      ] },
      { type: 'p', text: 'Follow these and WhatsApp becomes your most responsive channel. We are building Flazyn so the right way is also the easy way.' },
    ],
  },
  {
    slug: 'from-spreadsheet-to-pipeline',
    title: 'From spreadsheet to pipeline in an afternoon',
    description: 'A practical checklist for moving your leads out of a spreadsheet and into a real sales pipeline.',
    tag: 'Playbook',
    readTime: '4 min read',
    date: '2026-09-30',
    author: 'Flazyn Team',
    image: '/images/blog-3.webp',
    imageAlt: 'Two colleagues working at computers in a bright office',
    body: [
      { type: 'p', text: 'Most teams start with a spreadsheet, and that is fine — until two people update the same row, a lead is forgotten for a week, and nobody knows which deals are real.' },
      { type: 'h2', text: 'Step 1: Decide your stages' },
      { type: 'p', text: 'Keep it simple. Four to six stages that describe what the customer has done, not what you hope they will do: New, Contacted, Qualified, Proposal, Won, Lost.' },
      { type: 'h2', text: 'Step 2: Clean before you import' },
      { type: 'ul', items: [
        'One row per person, with a phone number or email on every row.',
        'Remove duplicates and test entries.',
        'Add a “source” column so you learn where leads come from.',
        'Record whether each contact agreed to be messaged.',
      ] },
      { type: 'h2', text: 'Step 3: Import and assign' },
      { type: 'p', text: 'Export your sheet as CSV, map the columns to your CRM fields and import. Flazyn is designed to spot duplicate emails and phone numbers during import, then let you assign each lead to an owner so nothing sits unclaimed.' },
      { type: 'h2', text: 'Step 4: Agree on one rule' },
      { type: 'p', text: 'Every lead has an owner and a next step with a date. That single habit is what turns a list of names into a pipeline you can trust.' },
    ],
  },
  {
    slug: 'why-design-matters-in-a-crm',
    title: 'Why design matters in a CRM',
    description: 'A CRM only works if people use it. Here is why calm, fast design leads to better data and better sales.',
    tag: 'Product',
    readTime: '3 min read',
    date: '2026-09-30',
    author: 'Flazyn Team',
    image: '/images/blog-4.webp',
    imageAlt: 'Two colleagues discussing work on a laptop',
    body: [
      { type: 'p', text: 'Every sales leader knows the problem: the CRM is only as good as the data in it, and the data is only as good as the team’s willingness to open the CRM.' },
      { type: 'p', text: 'When a tool is slow, cluttered or confusing, people route around it. Notes live in chat apps. Deals live in someone’s head. The CRM becomes a place you update on Friday afternoon.' },
      { type: 'h2', text: 'Design is adoption' },
      { type: 'p', text: 'We are designing Flazyn around the moments that matter: seeing who needs a reply, replying, and moving the deal forward. Fewer clicks, clear next steps, and screens that feel calm even when the pipeline is busy.' },
      { type: 'p', text: 'A CRM your team enjoys opening is a CRM with complete data. And complete data is where good decisions come from.' },
    ],
  },
];
